name: Renovate SelfHosted
on:
  workflow_dispatch: # Allows manual triggering from the Actions tab
  schedule:
    # Configure your desired schedule. This example runs daily at 3:00 AM UTC.
    # Use crontab syntax: https://crontab.guru/
    - cron: '0 3 * * *'

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v42.0.1
        with:
          configurationFile: .github/renovate.json
          docker-cmd-file: .github/renovate-entrypoint.sh
          docker-user: root # You might not need this anymore
          token: ${{ secrets.RENOVATE_TOKEN }}
